version: '3.8'

services:
  # Backend Laravel
  laravel:
    build:
      context: ./task-management-backend
      dockerfile: Dockerfile
    container_name: task-management-backend
    restart: unless-stopped
    volumes:
      - ./task-management-backend:/var/www
    networks:
      - task-network

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: task-management-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./task-management-backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - task-network

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: task-management-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_PASSWORD: root123
      MYSQL_USER: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - task-network

  # Vue.js (desarrollo)
  vue:
    build:
      context: ./task-management-frontend
      dockerfile: Dockerfile
    container_name: task-management-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./task-management-frontend:/app
      - /app/node_modules
    networks:
      - task-network

volumes:
  mysql_data:

networks:
  task-network:
    driver: bridge